// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: favorite.proto

package favorite_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FavoriteAction_GiveFavoriteService_FullMethodName = "/favorite_grpc.FavoriteAction/GiveFavoriteService"
)

// FavoriteActionClient is the client API for FavoriteAction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FavoriteActionClient interface {
	GiveFavoriteService(ctx context.Context, in *DouYinFavoriteActionRequest, opts ...grpc.CallOption) (*DouYinFavoriteActionResponse, error)
}

type favoriteActionClient struct {
	cc grpc.ClientConnInterface
}

func NewFavoriteActionClient(cc grpc.ClientConnInterface) FavoriteActionClient {
	return &favoriteActionClient{cc}
}

func (c *favoriteActionClient) GiveFavoriteService(ctx context.Context, in *DouYinFavoriteActionRequest, opts ...grpc.CallOption) (*DouYinFavoriteActionResponse, error) {
	out := new(DouYinFavoriteActionResponse)
	err := c.cc.Invoke(ctx, FavoriteAction_GiveFavoriteService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FavoriteActionServer is the server API for FavoriteAction service.
// All implementations must embed UnimplementedFavoriteActionServer
// for forward compatibility
type FavoriteActionServer interface {
	GiveFavoriteService(context.Context, *DouYinFavoriteActionRequest) (*DouYinFavoriteActionResponse, error)
	mustEmbedUnimplementedFavoriteActionServer()
}

// UnimplementedFavoriteActionServer must be embedded to have forward compatible implementations.
type UnimplementedFavoriteActionServer struct {
}

func (UnimplementedFavoriteActionServer) GiveFavoriteService(context.Context, *DouYinFavoriteActionRequest) (*DouYinFavoriteActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GiveFavoriteService not implemented")
}
func (UnimplementedFavoriteActionServer) mustEmbedUnimplementedFavoriteActionServer() {}

// UnsafeFavoriteActionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FavoriteActionServer will
// result in compilation errors.
type UnsafeFavoriteActionServer interface {
	mustEmbedUnimplementedFavoriteActionServer()
}

func RegisterFavoriteActionServer(s grpc.ServiceRegistrar, srv FavoriteActionServer) {
	s.RegisterService(&FavoriteAction_ServiceDesc, srv)
}

func _FavoriteAction_GiveFavoriteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouYinFavoriteActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteActionServer).GiveFavoriteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavoriteAction_GiveFavoriteService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteActionServer).GiveFavoriteService(ctx, req.(*DouYinFavoriteActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FavoriteAction_ServiceDesc is the grpc.ServiceDesc for FavoriteAction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FavoriteAction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "favorite_grpc.FavoriteAction",
	HandlerType: (*FavoriteActionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GiveFavoriteService",
			Handler:    _FavoriteAction_GiveFavoriteService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "favorite.proto",
}

const (
	FavoriteList_FavoriteListService_FullMethodName = "/favorite_grpc.FavoriteList/FavoriteListService"
)

// FavoriteListClient is the client API for FavoriteList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FavoriteListClient interface {
	FavoriteListService(ctx context.Context, in *DouYinFavoriteListRequest, opts ...grpc.CallOption) (*DouYinFavoriteListResponse, error)
}

type favoriteListClient struct {
	cc grpc.ClientConnInterface
}

func NewFavoriteListClient(cc grpc.ClientConnInterface) FavoriteListClient {
	return &favoriteListClient{cc}
}

func (c *favoriteListClient) FavoriteListService(ctx context.Context, in *DouYinFavoriteListRequest, opts ...grpc.CallOption) (*DouYinFavoriteListResponse, error) {
	out := new(DouYinFavoriteListResponse)
	err := c.cc.Invoke(ctx, FavoriteList_FavoriteListService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FavoriteListServer is the server API for FavoriteList service.
// All implementations must embed UnimplementedFavoriteListServer
// for forward compatibility
type FavoriteListServer interface {
	FavoriteListService(context.Context, *DouYinFavoriteListRequest) (*DouYinFavoriteListResponse, error)
	mustEmbedUnimplementedFavoriteListServer()
}

// UnimplementedFavoriteListServer must be embedded to have forward compatible implementations.
type UnimplementedFavoriteListServer struct {
}

func (UnimplementedFavoriteListServer) FavoriteListService(context.Context, *DouYinFavoriteListRequest) (*DouYinFavoriteListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FavoriteListService not implemented")
}
func (UnimplementedFavoriteListServer) mustEmbedUnimplementedFavoriteListServer() {}

// UnsafeFavoriteListServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FavoriteListServer will
// result in compilation errors.
type UnsafeFavoriteListServer interface {
	mustEmbedUnimplementedFavoriteListServer()
}

func RegisterFavoriteListServer(s grpc.ServiceRegistrar, srv FavoriteListServer) {
	s.RegisterService(&FavoriteList_ServiceDesc, srv)
}

func _FavoriteList_FavoriteListService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouYinFavoriteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteListServer).FavoriteListService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavoriteList_FavoriteListService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteListServer).FavoriteListService(ctx, req.(*DouYinFavoriteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FavoriteList_ServiceDesc is the grpc.ServiceDesc for FavoriteList service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FavoriteList_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "favorite_grpc.FavoriteList",
	HandlerType: (*FavoriteListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FavoriteListService",
			Handler:    _FavoriteList_FavoriteListService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "favorite.proto",
}
