// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: message.proto

package message_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChatService_CheckMessage_FullMethodName = "/message_grpc.ChatService/CheckMessage"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	CheckMessage(ctx context.Context, in *DouYinMessageChatRequest, opts ...grpc.CallOption) (*DouYinMessageChatResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) CheckMessage(ctx context.Context, in *DouYinMessageChatRequest, opts ...grpc.CallOption) (*DouYinMessageChatResponse, error) {
	out := new(DouYinMessageChatResponse)
	err := c.cc.Invoke(ctx, ChatService_CheckMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility
type ChatServiceServer interface {
	CheckMessage(context.Context, *DouYinMessageChatRequest) (*DouYinMessageChatResponse, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (UnimplementedChatServiceServer) CheckMessage(context.Context, *DouYinMessageChatRequest) (*DouYinMessageChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckMessage not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_CheckMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouYinMessageChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CheckMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_CheckMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CheckMessage(ctx, req.(*DouYinMessageChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message_grpc.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckMessage",
			Handler:    _ChatService_CheckMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

const (
	MessageAction_Chat_FullMethodName = "/message_grpc.MessageAction/Chat"
)

// MessageActionClient is the client API for MessageAction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageActionClient interface {
	Chat(ctx context.Context, in *DouYinMessageActionRequest, opts ...grpc.CallOption) (*DouYinMessageActionResponse, error)
}

type messageActionClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageActionClient(cc grpc.ClientConnInterface) MessageActionClient {
	return &messageActionClient{cc}
}

func (c *messageActionClient) Chat(ctx context.Context, in *DouYinMessageActionRequest, opts ...grpc.CallOption) (*DouYinMessageActionResponse, error) {
	out := new(DouYinMessageActionResponse)
	err := c.cc.Invoke(ctx, MessageAction_Chat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageActionServer is the server API for MessageAction service.
// All implementations must embed UnimplementedMessageActionServer
// for forward compatibility
type MessageActionServer interface {
	Chat(context.Context, *DouYinMessageActionRequest) (*DouYinMessageActionResponse, error)
	mustEmbedUnimplementedMessageActionServer()
}

// UnimplementedMessageActionServer must be embedded to have forward compatible implementations.
type UnimplementedMessageActionServer struct {
}

func (UnimplementedMessageActionServer) Chat(context.Context, *DouYinMessageActionRequest) (*DouYinMessageActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedMessageActionServer) mustEmbedUnimplementedMessageActionServer() {}

// UnsafeMessageActionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageActionServer will
// result in compilation errors.
type UnsafeMessageActionServer interface {
	mustEmbedUnimplementedMessageActionServer()
}

func RegisterMessageActionServer(s grpc.ServiceRegistrar, srv MessageActionServer) {
	s.RegisterService(&MessageAction_ServiceDesc, srv)
}

func _MessageAction_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouYinMessageActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageActionServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageAction_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageActionServer).Chat(ctx, req.(*DouYinMessageActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageAction_ServiceDesc is the grpc.ServiceDesc for MessageAction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageAction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message_grpc.MessageAction",
	HandlerType: (*MessageActionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _MessageAction_Chat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
